"""initial_schema

Revision ID: 0aeebda00bb4
Revises: 
Create Date: 2026-03-23 20:25:39.649124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aeebda00bb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_queue_agent_id'), ['agent_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('ENGINEER', 'REVIEWER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=256), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=8), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('current_task', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('compliance_refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('network_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cidr', sa.String(length=43), nullable=False),
    sa.Column('connection_scenario', sa.String(length=32), nullable=True),
    sa.Column('selected_test_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISCOVERING', 'SCANNING', 'COMPLETE', 'ERROR', name='networkscanstatus'), nullable=True),
    sa.Column('devices_found', sa.JSON(), nullable=True),
    sa.Column('run_ids', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_whitelists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=256), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('template_file', sa.String(length=512), nullable=True),
    sa.Column('template_url', sa.String(length=1024), nullable=True),
    sa.Column('report_type', sa.String(length=16), nullable=False),
    sa.Column('cell_mappings', sa.JSON(), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('compliance_standards', sa.JSON(), nullable=True),
    sa.Column('branding_colours', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('model_pattern', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_whitelist_id', sa.String(length=36), nullable=True),
    sa.Column('additional_tests', sa.JSON(), nullable=True),
    sa.Column('safe_mode', sa.JSON(), nullable=True),
    sa.Column('fingerprint_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['default_whitelist_id'], ['protocol_whitelists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('device_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_profiles_manufacturer'), ['manufacturer'], unique=False)

    op.create_table('test_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('test_ids', sa.JSON(), nullable=False),
    sa.Column('whitelist_id', sa.String(length=36), nullable=True),
    sa.Column('cell_mappings', sa.JSON(), nullable=True),
    sa.Column('report_config', sa.JSON(), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['whitelist_id'], ['protocol_whitelists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('category', sa.Enum('CAMERA', 'CONTROLLER', 'INTERCOM', 'ACCESS_PANEL', 'LIGHTING', 'HVAC', 'IOT_SENSOR', 'METER', 'UNKNOWN', name='devicecategory'), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'IDENTIFIED', 'TESTING', 'TESTED', 'QUALIFIED', 'FAILED', name='devicestatus'), nullable=True),
    sa.Column('oui_vendor', sa.String(length=128), nullable=True),
    sa.Column('os_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('open_ports', sa.JSON(), nullable=True),
    sa.Column('discovery_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('discovered_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discovered_by'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['device_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_ip_address'), ['ip_address'], unique=False)

    op.create_table('test_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_template_id', sa.String(length=36), nullable=True),
    sa.Column('test_configs', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_template_id'], ['test_templates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('engineer_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('connection_scenario', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SELECTING_INTERFACE', 'SYNCING', 'RUNNING', 'PAUSED', 'AWAITING_MANUAL', 'COMPLETED', 'FAILED', 'CANCELLED', name='testrunstatus'), nullable=True),
    sa.Column('overall_verdict', sa.Enum('PASS', 'QUALIFIED_PASS', 'FAIL', 'INCOMPLETE', name='testrunverdict'), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('completed_tests', sa.Integer(), nullable=True),
    sa.Column('passed_tests', sa.Integer(), nullable=True),
    sa.Column('failed_tests', sa.Integer(), nullable=True),
    sa.Column('advisory_tests', sa.Integer(), nullable=True),
    sa.Column('na_tests', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('synopsis_status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['test_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_runs_device_id'), ['device_id'], unique=False)

    op.create_table('nessus_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk_factor', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=8), nullable=True),
    sa.Column('plugin_output', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cve_ids', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nessus_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nessus_findings_run_id'), ['run_id'], unique=False)

    op.create_table('test_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=8), nullable=False),
    sa.Column('test_name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.Enum('AUTOMATIC', 'GUIDED_MANUAL', 'NESSUS_IMPORT', name='testtier'), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', 'ADVISORY', 'INFO', 'NA', 'ERROR', 'PENDING', 'RUNNING', 'SKIPPED_SAFE_MODE', name='testverdict'), nullable=True),
    sa.Column('is_essential', sa.String(length=3), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('comment_override', sa.Text(), nullable=True),
    sa.Column('engineer_notes', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('evidence_files', sa.JSON(), nullable=True),
    sa.Column('compliance_map', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_results_test_run_id'), ['test_run_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('test_result_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_test_run_id'), ['test_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_test_run_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_test_run_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_test_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('nessus_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nessus_findings_run_id'))

    op.drop_table('nessus_findings')
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_device_id'))

    op.drop_table('test_runs')
    op.drop_table('test_plans')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_ip_address'))

    op.drop_table('devices')
    op.drop_table('test_templates')
    with op.batch_alter_table('device_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_profiles_manufacturer'))

    op.drop_table('device_profiles')
    op.drop_table('report_configs')
    op.drop_table('protocol_whitelists')
    op.drop_table('network_scans')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_queue_agent_id'))

    op.drop_table('sync_queue')
    # ### end Alembic commands ###
