import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { profilesApi } from '@/lib/api'
import {
  Camera, Cpu, Radio, Mic, Box, ChevronRight, Shield, Check,
  Sparkles, Trash2, Loader2, Plus, Pencil,
} from 'lucide-react'
import toast from 'react-hot-toast'
import ProfileEditorDialog from '@/components/profiles/ProfileEditorDialog'

interface DeviceProfile {
  id: string
  name: string
  icon: React.ElementType
  description: string
  color: string
  testIds: string[]
  autoGenerated?: boolean
}

const BUILTIN_PROFILES: DeviceProfile[] = [
  {
    id: 'camera',
    name: 'IP Camera',
    icon: Camera,
    description: 'RTSP/ONVIF video surveillance cameras with streaming capabilities',
    color: 'blue',
    testIds: ['U01', 'U02', 'U06', 'U07', 'U08', 'U09', 'U10', 'U11', 'U12', 'U15', 'U16', 'U19', 'U34', 'U35', 'U36'],
  },
  {
    id: 'controller',
    name: 'Access Controller',
    icon: Cpu,
    description: 'Door controllers, alarm panels, and building management systems',
    color: 'purple',
    testIds: ['U01', 'U02', 'U06', 'U08', 'U10', 'U11', 'U15', 'U16', 'U19', 'U34'],
  },
  {
    id: 'iot_gateway',
    name: 'IoT Gateway',
    icon: Radio,
    description: 'Edge gateways bridging IoT protocols (Zigbee, Z-Wave, BACnet)',
    color: 'green',
    testIds: ['U01', 'U02', 'U06', 'U07', 'U08', 'U10', 'U11', 'U12', 'U15', 'U16', 'U19'],
  },
  {
    id: 'intercom',
    name: 'Intercom / VoIP',
    icon: Mic,
    description: 'SIP-based intercoms, door stations, and VoIP endpoints',
    color: 'amber',
    testIds: ['U01', 'U02', 'U06', 'U08', 'U10', 'U11', 'U15', 'U16', 'U34', 'U35'],
  },
  {
    id: 'generic',
    name: 'Generic Device',
    icon: Box,
    description: 'Default profile for uncategorised network devices',
    color: 'zinc',
    testIds: ['U01', 'U02', 'U06', 'U08', 'U10', 'U16'],
  },
]

const colorMap: Record<string, { bg: string; border: string; text: string; badge: string; iconBg: string; ring: string }> = {
  blue: { bg: 'bg-blue-50 dark:bg-blue-950/30', border: 'border-blue-200 dark:border-blue-800', text: 'text-blue-700 dark:text-blue-300', badge: 'bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300', iconBg: 'bg-blue-100 dark:bg-blue-900', ring: 'ring-blue-400/30' },
  purple: { bg: 'bg-purple-50 dark:bg-purple-950/30', border: 'border-purple-200 dark:border-purple-800', text: 'text-purple-700 dark:text-purple-300', badge: 'bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300', iconBg: 'bg-purple-100 dark:bg-purple-900', ring: 'ring-purple-400/30' },
  green: { bg: 'bg-green-50 dark:bg-green-950/30', border: 'border-green-200 dark:border-green-800', text: 'text-green-700 dark:text-green-300', badge: 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300', iconBg: 'bg-green-100 dark:bg-green-900', ring: 'ring-green-400/30' },
  amber: { bg: 'bg-amber-50 dark:bg-amber-950/30', border: 'border-amber-200 dark:border-amber-800', text: 'text-amber-700 dark:text-amber-300', badge: 'bg-amber-100 dark:bg-amber-900 text-amber-700 dark:text-amber-300', iconBg: 'bg-amber-100 dark:bg-amber-900', ring: 'ring-amber-400/30' },
  zinc: { bg: 'bg-zinc-50 dark:bg-slate-800/50', border: 'border-zinc-200 dark:border-slate-700/50', text: 'text-zinc-700 dark:text-slate-300', badge: 'bg-zinc-100 dark:bg-slate-800 text-zinc-700 dark:text-slate-300', iconBg: 'bg-zinc-100 dark:bg-slate-800', ring: 'ring-zinc-400/30' },
  indigo: { bg: 'bg-indigo-50 dark:bg-indigo-950/30', border: 'border-indigo-200 dark:border-indigo-800', text: 'text-indigo-700 dark:text-indigo-300', badge: 'bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300', iconBg: 'bg-indigo-100 dark:bg-indigo-900', ring: 'ring-indigo-400/30' },
}

export default function DeviceProfilesPage() {
  const [selectedProfile, setSelectedProfile] = useState<string | null>(null)
  const [editorOpen, setEditorOpen] = useState(false)
  const [editingProfile, setEditingProfile] = useState<any>(null)
  const queryClient = useQueryClient()

  const { data: apiProfiles = [], isLoading } = useQuery({
    queryKey: ['device-profiles'],
    queryFn: () => profilesApi.list({ limit: 200 }).then((r) => r.data),
  })

  // Convert API auto-learned profiles to the same shape as built-in ones
  const autoLearnedProfiles: DeviceProfile[] = (apiProfiles as any[])
    .filter((p: any) => p.auto_generated)
    .map((p: any) => ({
      id: p.id,
      name: p.name,
      icon: Sparkles,
      description: p.description || `Auto-learned from ${p.manufacturer}`,
      color: 'indigo',
      testIds: p.fingerprint_rules?.skip_test_ids
        ? Array.from({ length: 43 }, (_, i) => `U${String(i + 1).padStart(2, '0')}`).filter(
            (t) => !p.fingerprint_rules.skip_test_ids.includes(t)
          )
        : [],
      autoGenerated: true,
    }))

  const allProfiles = [...BUILTIN_PROFILES, ...autoLearnedProfiles]
  const selected = allProfiles.find((p) => p.id === selectedProfile)

  const handleDeleteProfile = async (profileId: string) => {
    try {
      await profilesApi.delete(profileId)
      toast.success('Profile deleted')
      setSelectedProfile(null)
      queryClient.invalidateQueries({ queryKey: ['device-profiles'] })
    } catch {
      toast.error('Failed to delete profile')
    }
  }

  const handleOpenEditor = (apiProfile?: any) => {
    if (apiProfile) {
      setEditingProfile({
        id: apiProfile.id,
        name: apiProfile.name,
        manufacturer: apiProfile.manufacturer,
        model_pattern: apiProfile.model_pattern || '',
        category: apiProfile.category,
        description: apiProfile.description || '',
        fingerprint_rules: apiProfile.fingerprint_rules || {
          required_ports: [], vendors: [], skip_test_ids: [],
        },
      })
    } else {
      setEditingProfile(null)
    }
    setEditorOpen(true)
  }

  const handleSaveProfile = async (data: any) => {
    try {
      if (data.id) {
        await profilesApi.update(data.id, {
          name: data.name,
          manufacturer: data.manufacturer,
          model_pattern: data.model_pattern,
          category: data.category,
          description: data.description,
          fingerprint_rules: data.fingerprint_rules,
        })
        toast.success('Profile updated')
      } else {
        await profilesApi.create({
          name: data.name,
          manufacturer: data.manufacturer,
          model_pattern: data.model_pattern,
          category: data.category,
          description: data.description,
          fingerprint_rules: data.fingerprint_rules,
        } as any)
        toast.success('Profile created')
      }
      queryClient.invalidateQueries({ queryKey: ['device-profiles'] })
    } catch (err: any) {
      toast.error(err?.response?.data?.detail || 'Failed to save profile')
      throw err
    }
  }

  // Find the raw API profile for editing
  const selectedApiProfile = (apiProfiles as any[]).find((p: any) => p.id === selectedProfile)

  return (
    <div className="page-container">
      <div className="flex items-start justify-between mb-5">
        <div>
          <h1 className="section-title">Device Profiles</h1>
          <p className="section-subtitle">
            Pre-configured test suites tailored for specific device categories.
            The smart profiler automatically detects device types and skips irrelevant tests.
          </p>
        </div>
        <button
          onClick={() => handleOpenEditor()}
          className="btn-primary text-sm flex-shrink-0"
        >
          <Plus className="w-4 h-4" />
          New Profile
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-3 mb-6">
        {allProfiles.map((profile) => {
          const c = colorMap[profile.color] || colorMap.zinc
          const isSelected = selectedProfile === profile.id
          const Icon = profile.icon
          return (
            <button
              key={profile.id}
              onClick={() => setSelectedProfile(isSelected ? null : profile.id)}
              className={`text-left p-4 rounded-xl border-2 transition-all duration-200 ${
                isSelected
                  ? `${c.bg} ${c.border} ring-2 ring-offset-1 ${c.ring}`
                  : 'border-zinc-200 dark:border-slate-700/50 hover:border-zinc-300 dark:hover:border-slate-600 bg-white dark:bg-dark-card'
              }`}
            >
              <div className={`w-10 h-10 rounded-lg ${c.iconBg} flex items-center justify-center mb-3`}>
                <Icon className={`w-5 h-5 ${c.text}`} />
              </div>
              <div className="flex items-center gap-1.5 mb-1">
                <h3 className={`text-sm font-semibold ${isSelected ? c.text : 'text-zinc-900 dark:text-slate-100'}`}>
                  {profile.name}
                </h3>
                {profile.autoGenerated && (
                  <span className="text-[9px] font-medium px-1.5 py-0.5 rounded-full bg-indigo-100 dark:bg-indigo-900 text-indigo-600 dark:text-indigo-400">
                    Auto-learned
                  </span>
                )}
              </div>
              <p className="text-xs text-zinc-500 dark:text-slate-400 line-clamp-2 mb-2">
                {profile.description}
              </p>
              <div className="flex items-center justify-between">
                <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${c.badge}`}>
                  {profile.testIds.length} tests
                </span>
                {isSelected && <Check className={`w-4 h-4 ${c.text}`} />}
              </div>
            </button>
          )
        })}
        {isLoading && (
          <div className="flex items-center justify-center p-4">
            <Loader2 className="w-5 h-5 animate-spin text-zinc-400" />
          </div>
        )}
      </div>

      {selected && (
        <div className="card p-5">
          <div className="flex items-center gap-3 mb-4">
            <div className={`w-8 h-8 rounded-lg ${(colorMap[selected.color] || colorMap.zinc).iconBg} flex items-center justify-center`}>
              <selected.icon className={`w-4 h-4 ${(colorMap[selected.color] || colorMap.zinc).text}`} />
            </div>
            <div className="flex-1">
              <h3 className="text-sm font-semibold text-zinc-900 dark:text-slate-100">
                {selected.name} — Included Tests
              </h3>
              <p className="text-xs text-zinc-500">
                {selected.testIds.length} tests will run when this profile is assigned
              </p>
            </div>
            {selected.autoGenerated && (
              <div className="flex items-center gap-1">
                <button
                  onClick={() => handleOpenEditor(selectedApiProfile)}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-lg text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/30 transition-colors"
                >
                  <Pencil className="w-3.5 h-3.5" />
                  Edit
                </button>
                <button
                  onClick={() => handleDeleteProfile(selected.id)}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-lg text-red-600 hover:bg-red-50 dark:hover:bg-red-950/30 transition-colors"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  Delete
                </button>
              </div>
            )}
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-2">
            {selected.testIds.map((testId) => (
              <div
                key={testId}
                className="flex items-center gap-2 px-3 py-2 rounded-lg bg-zinc-50 dark:bg-slate-800 border border-zinc-200 dark:border-slate-700/50"
              >
                <Shield className="w-3.5 h-3.5 text-brand-500 flex-shrink-0" />
                <span className="text-xs font-mono text-zinc-700 dark:text-slate-300">{testId}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {!selected && (
        <div className="card p-8 text-center">
          <div className="w-12 h-12 rounded-full bg-zinc-100 dark:bg-slate-800 flex items-center justify-center mx-auto mb-3">
            <ChevronRight className="w-6 h-6 text-zinc-400" />
          </div>
          <p className="text-sm text-zinc-500 dark:text-slate-400">
            Select a device profile above to see the included test suite
          </p>
        </div>
      )}

      <ProfileEditorDialog
        open={editorOpen}
        onOpenChange={setEditorOpen}
        onSave={handleSaveProfile}
        profile={editingProfile}
      />
    </div>
  )
}
