param(
    [string]$OutputDir = "reports/production",
    [string]$BaseUrl = "",
    [string]$AdminUser = "admin",
    [string]$AdminPass = "",
    [string]$MetricsApiKey = "",
    [string[]]$PilotDeviceIps = @(),
    [switch]$AllowWideRanges,
    [switch]$SkipBackupRestore,
    [switch]$SkipPilotReport
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$EvidenceDir = if ([System.IO.Path]::IsPathRooted($OutputDir)) {
    $OutputDir
} else {
    Join-Path $RepoRoot $OutputDir
}
$Checks = New-Object System.Collections.Generic.List[object]

function Add-Check {
    param(
        [string]$Name,
        [string]$Status,
        [string]$Message,
        [string]$Path = ""
    )
    $Checks.Add([pscustomobject]@{
        name = $Name
        status = $Status
        message = $Message
        path = $Path
    }) | Out-Null
}

function Test-EvidenceJson {
    param([string]$Path)
    try {
        $evidence = Get-Content $Path -Raw | ConvertFrom-Json
        if ($evidence -is [System.Array]) {
            $items = @($evidence)
        } elseif ($evidence.PSObject.Properties["checks"]) {
            $items = @($evidence.checks)
        } else {
            $items = @($evidence)
        }
        $badCount = @($items | Where-Object { $_.status -eq "error" -or $_.status -eq "warning" }).Count
        return ($items.Count -gt 0 -and $badCount -eq 0)
    } catch {
        return $false
    }
}

function Invoke-EvidenceScript {
    param(
        [string]$Name,
        [string]$OutputFile,
        [string[]]$Arguments
    )

    $fullOutputPath = Join-Path $EvidenceDir $OutputFile
    $scriptPath = Join-Path $RepoRoot $Arguments[0]
    $scriptArgs = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", $scriptPath)
    if ($Arguments.Count -gt 1) {
        $scriptArgs += $Arguments[1..($Arguments.Count - 1)]
    }
    $scriptArgs += "-Json"

    $output = & powershell @scriptArgs 2>&1
    $exitCode = $LASTEXITCODE
    $output | Set-Content -Path $fullOutputPath -Encoding UTF8

    if ($exitCode -eq 0 -and (Test-EvidenceJson $fullOutputPath)) {
        Add-Check $Name "ok" "Evidence collected." $fullOutputPath
    } elseif ($exitCode -eq 0) {
        Add-Check $Name "warning" "Evidence file contains warning checks." $fullOutputPath
    } else {
        Add-Check $Name "error" "Evidence command failed." $fullOutputPath
    }
    return $fullOutputPath
}

New-Item -ItemType Directory -Force -Path $EvidenceDir | Out-Null

$envFile = Join-Path $EvidenceDir "production-gate-env-$Timestamp.ps1"
$bundleFile = Join-Path $EvidenceDir "production-evidence-bundle-$Timestamp.json"
$envLines = @(
    "# Generated by scripts/collect-production-evidence.ps1",
    "# Dot-source this file before running scripts/production-gate.ps1."
)

if ($SkipBackupRestore) {
    Add-Check "Backup restore drill" "warning" "Skipped by request."
} else {
    $backupFile = Invoke-EvidenceScript "Backup restore drill" "backup-restore-drill-$Timestamp.json" @(
        "scripts/backup-restore-drill.ps1",
        "-BackupDir", (Join-Path $EvidenceDir "restore-drills")
    )
    if ((Test-EvidenceJson $backupFile)) {
        $envLines += "`$env:EDQ_BACKUP_RESTORE_DRILL_EVIDENCE = '$backupFile'"
    }
}

$monitorArgs = @("scripts/monitor-health.ps1")
if ($BaseUrl) { $monitorArgs += @("-BaseUrl", $BaseUrl) }
if ($AdminUser) { $monitorArgs += @("-AdminUser", $AdminUser) }
if ($AdminPass) { $monitorArgs += @("-AdminPass", $AdminPass) }
if ($MetricsApiKey) { $monitorArgs += @("-MetricsApiKey", $MetricsApiKey) }
$monitorFile = Invoke-EvidenceScript "Monitoring" "monitor-health-$Timestamp.json" $monitorArgs
if ((Test-EvidenceJson $monitorFile)) {
    $envLines += "`$env:EDQ_MONITORING_EVIDENCE = '$monitorFile'"
}

$scannerArgs = @("scripts/scanner-governance-report.ps1")
if ($BaseUrl) { $scannerArgs += @("-BaseUrl", $BaseUrl) }
if ($AdminUser) { $scannerArgs += @("-AdminUser", $AdminUser) }
if ($AdminPass) { $scannerArgs += @("-AdminPass", $AdminPass) }
if ($AllowWideRanges) { $scannerArgs += "-AllowWideRanges" }
$scannerFile = Invoke-EvidenceScript "Scanner governance" "scanner-governance-$Timestamp.json" $scannerArgs
if ((Test-EvidenceJson $scannerFile)) {
    $envLines += "`$env:EDQ_SCAN_GOVERNANCE_EVIDENCE = '$scannerFile'"
}

if ($SkipPilotReport) {
    Add-Check "Real-device pilot" "warning" "Skipped by request."
} elseif ($PilotDeviceIps.Count -eq 0) {
    Add-Check "Real-device pilot" "error" "Pass -PilotDeviceIps with every expected pilot device IP."
} else {
    $pilotArgs = @("scripts/real-device-pilot-report.ps1", "-DeviceIps") + $PilotDeviceIps
    if ($BaseUrl) { $pilotArgs += @("-BaseUrl", $BaseUrl) }
    if ($AdminUser) { $pilotArgs += @("-AdminUser", $AdminUser) }
    if ($AdminPass) { $pilotArgs += @("-AdminPass", $AdminPass) }
    $pilotFile = Invoke-EvidenceScript "Real-device pilot" "real-device-pilot-$Timestamp.json" $pilotArgs
    if ((Test-EvidenceJson $pilotFile)) {
        $envLines += "`$env:EDQ_REAL_DEVICE_PILOT_EVIDENCE = '$pilotFile'"
    }
}

$envLines | Set-Content -Path $envFile -Encoding UTF8
$bundle = [pscustomobject]@{
    generated_at = (Get-Date).ToString("o")
    evidence_directory = $EvidenceDir
    env_file = $envFile
    checks = $Checks
}
$bundle | ConvertTo-Json -Depth 6 | Set-Content -Path $bundleFile -Encoding UTF8

Write-Host ""
Write-Host "EDQ production evidence bundle"
Write-Host ""
foreach ($check in $Checks) {
    $color = switch ($check.status) {
        "error" { "Red" }
        "warning" { "Yellow" }
        default { "Green" }
    }
    $suffix = if ($check.path) { " ($($check.path))" } else { "" }
    Write-Host ("[{0}] {1}: {2}{3}" -f $check.status.ToUpperInvariant(), $check.name, $check.message, $suffix) -ForegroundColor $color
}
Write-Host ""
Write-Host "Evidence bundle: $bundleFile"
Write-Host "Gate environment: $envFile"

if (@($Checks | Where-Object { $_.status -eq "error" }).Count -gt 0) {
    exit 1
}
